/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 15:26:06 GMT 2020
 */

package ch.lambdaj.function.aggregate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.lambdaj.function.aggregate.MaxOnArgument;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChooserOnArgument_ESTest extends ChooserOnArgument_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MaxOnArgument<String, Object> maxOnArgument0 = null;
      try {
        maxOnArgument0 = new MaxOnArgument<String, Object>((Object) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // ch/lambdaj/proxy/InvocationInterceptor
         //
         verifyException("ch.lambdaj.function.aggregate.ChooserOnArgument", e);
      }
  }
}
