/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 15:29:39 GMT 2020
 */

package ch.lambdaj.function.aggregate;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.lambdaj.function.aggregate.SumDouble;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InitializedPairAggregator_ESTest extends InitializedPairAggregator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SumDouble sumDouble0 = new SumDouble((Double) null);
      Double double0 = sumDouble0.emptyItem();
      assertNull(double0);
  }
}
