/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 15:27:18 GMT 2020
 */

package ch.lambdaj.function.aggregate;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.lambdaj.function.aggregate.Concat;
import java.util.Iterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Concat_ESTest extends Concat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Concat concat0 = new Concat("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Concat concat0 = new Concat();
      Object object0 = concat0.aggregate((Iterator<?>) null);
      assertEquals("", object0);
  }
}
