/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 15:35:33 GMT 2020
 */

package ch.lambdaj.collection;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.lambdaj.collection.LambdaGroup;
import ch.lambdaj.group.Group;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LambdaGroup_ESTest extends LambdaGroup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LambdaGroup<LambdaGroup<Object>> lambdaGroup0 = new LambdaGroup<LambdaGroup<Object>>((Group<LambdaGroup<Object>>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.find((Object) "BG2iI,%Zp[q.EN");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.getHeads();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LambdaGroup<Object> lambdaGroup0 = new LambdaGroup<Object>((Group<Object>) null);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        lambdaGroup0.findGroup(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LambdaGroup<Object> lambdaGroup0 = new LambdaGroup<Object>((Group<Object>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.isLeaf();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.key();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.find("ch.lambdaj.group.LeafGroup");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.first();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LambdaGroup<Object> lambdaGroup0 = new LambdaGroup<Object>((Group<Object>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.subgroups();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LambdaGroup<Integer> lambdaGroup0 = new LambdaGroup<Integer>((Group<Integer>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.findGroup("=qr&=yO49");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LambdaGroup<String> lambdaGroup0 = new LambdaGroup<String>((Group<String>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.getHeadValue("R!SG#Cm<ADhbJ$,");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LambdaGroup<Object> lambdaGroup0 = new LambdaGroup<Object>((Group<Object>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.keySet();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LambdaGroup<Object> lambdaGroup0 = new LambdaGroup<Object>((Group<Object>) null);
      // Undeclared exception!
      try { 
        lambdaGroup0.findAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.lambdaj.collection.LambdaGroup", e);
      }
  }
}
